### ISSUE TITLE
Can't instantiate Nim type in Godot

### ISSUE THREAD

**Issue by NieznanywInternetach** [godot-nim/gdext-nim#147]
Hello,
As a toy project of getting to know this extention, I tried implementing a scene manager tool, and [this file](https://github.com/EiTaNBaRiBoA/AsyncScene/blob/main/addons/AsyncSceneManager/AsyncScene.gd) to be exact, but after compilation Godot refused to instantiate it

I'm using v0.4.1 of this extention and the stable branch of Godot 4.3, on Windows 11
I previously succesfully created a small class adding a bunch of nodes at runtime, dubling provided int and displaying the result

When trying to attach the class via editor...
`editor/editor_data.cpp:597 - Parameter "p_object" is null.`
`editor/scene_tree_dock.cpp:2767 - Parameter "child" is null.`

... and code
`E 0:00:00:0477   main_menu.gd:6 @ _ready(): Class type: 'AsyncLoader' is not instantiable.`
`<C++ Error>    Parameter "o" is null.`
`<C++ Source>   modules/gdscript/gdscript.cpp:88 @ _new()`
`<Stack Trace>  main_menu.gd:6 @ _ready()`
`E 0:00:00:0477   main_menu.gd:8 @ _ready(): Parameter "p_child" is null.`
` <C++ Source>   scene/main/node.cpp:1566 @ add_child()`
`  <Stack Trace>  main_menu.gd:8 @ _ready()`

With this code being simple script attached to the scene root `Node`
```gdscript
extends Node
func _ready() -> void:
	var al = AsyncLoader.new()
	print(al) # this prints <null>
	self.add_child(al)
```
Compared to the original, I made a small design change as to make the location of AsyncLoader independent from where the scene is spawned. I believe it should not have any impact on this issue.
I had a couple of trials and errors, so my source code in Nim looks like this
```nim
import gdext
import gdext/classes / [gdNode, gdTimer, gdResourceLoader, gdEngine] 
import gdext/classes / [gdMainLoop, gdPackedScene, gdSceneTree]
from gdext/gen/localenums import ResourceLoader_ThreadLoadStatus
import gdext/core / [builtinindex]
# Nim implementation of 
# https://github.com/EiTaNBaRiBoA/AsyncScene/blob/main/addons/AsyncSceneManager/AsyncScene.gd
# on MIT license by Eitan (c) 2024 

# Maps ResourceLoader_ThreadLoadStatus values to human-readable strings
const statusNames: array[threadLoadInvalidResource..threadLoadLoaded, string] = [
  "THREAD_LOAD_INVALID_RESOURCE", 
  "THREAD_LOAD_IN_PROGRESS", 
  "THREAD_LOAD_FAILED", 
  "THREAD_LOAD_LOADED"
]

const ASYNCLOADER_NOT_INIT_MSG = "AsyncLoader not properly initialized! Use postReadyInitialization(...) first."

type 
  LoadingSceneOperation = enum  # Defines the different operations that can be performed with the scene loader
    ReplaceImmediate,           # Replaces the current scene immediately upon loading
    Replace,                    # Doesn't replace the scene immediately; call ChangeScene() to replace
    AdditiveImmediate,          # Adds the new scene as a child to the root node immediately upon loading
    Additive                    # Doesn't add the scene immediately; call ChangeScene() to add  

  AsyncLoader* = ptr object of Node
    timer* {.gdexport.}: Timer              # Timer for checking the loading status
    packedScenePath : String                # Path to the packed scene file
    myRes* {.gdexport.}: GdRef[PackedScene] # Loaded PackedScene resource
    currentSceneNode: Node                  # Instance of the loaded scene
    rootSceneNode* {.gdexport.}: Node       # Node the instance is to be added to
    progress: float = 0                     # Loading progress (0-100)
    isCompleted: bool = false               # Flag indicating if the scene has been loaded successfully
    changed: bool = false      # Flag to prevent multiple scene changes (for Replace and Additive operations)
    # Selected operation type for loading the scene
    typeOperation: LoadingSceneOperation = ReplaceImmediate
    initialized: bool = false


# Signal emitted when the scene loading is complete
proc onComplete*(self: AsyncLoader): Error {.gdsync, signal.}
# forward declaration
proc getStatusValue*(self: AsyncLoader): ResourceLoader_ThreadLoadStatus {.gdsync.}
proc additiveScene_internal(self: AsyncLoader) {.gdsync.}
proc changeImmediate_internal(self: AsyncLoader) {.gdsync.}
proc complete(self: AsyncLoader, isFailed: bool) {.gdsync.}

# Sets up the timer to check the loading status
proc setupUpdateSeconds_internal(self: AsyncLoader) {.gdsync.} =
  self.rootSceneNode.add_child(self.timer)

  self.timer.one_shot = false
  self.timer.autostart = true
  self.timer.setWaitTime(0.1)

  # Connect the timer timeout signal to _check_status
  discard self.timer.connect("timeout", self.callable("checkStatus_internal"))
  self.timer.start()


# Checks the loading status of the scene
proc checkStatus_internal(self: AsyncLoader) {.gdsync.} =
  if self.isCompleted: # Check if the scene is already loaded
    return

  var status = self.getStatusValue() # Get the loading status

  case status:
  of threadLoadLoaded:  # v from Reference to a Resource to Reference to a PackedScene
    self.myRes = ResourceLoader.loadThreadedGet(self.packedScenePath)[].PackedScene.asGdRef
    if self.typeOperation == ReplaceImmediate:
      self.changeImmediate_internal()
    elif self.typeOperation == AdditiveImmediate:
      self.additiveScene_internal()
    self.complete(false) # Mark the scene as loaded and stop the timer

  of threadLoadInvalidResource:
    self.complete(true) # Mark the scene loading as failed and stop the timer
  of threadLoadFailed:  
    self.complete(true) # Mark the scene loading as failed and stop the timer
  of threadLoadInProgress:
    var progressArr: Array # v returns a single float into the array
    discard ResourceLoader.loadThreadedGetStatus(self.packedScenePath, progressArr)
    self.progress = progressArr[0].get(Float) * 100


# Adds the loaded scene as a child of the root node
proc additiveScene_internal(self: AsyncLoader) {.gdsync.} =
  self.currentSceneNode = self.myRes[].instantiate()
  self.rootSceneNode.addChild(self.currentSceneNode)
  discard self.rootSceneNode.call_deferred("add_child", variant self.currentSceneNode)


# Replaces the current scene with the loaded scene
proc changeImmediate_internal(self: AsyncLoader) {.gdsync.} =
  self.currentSceneNode = self.rootSceneNode.getTree().getCurrentScene()
  
  if not self.currentSceneNode.isNil: # Queue the current scene for deletion if it exists
    self.currentSceneNode.queue_free()
  self.additiveScene_internal() # Add the loaded scene to the tree


# Called when the scene loading is complete
proc complete(self: AsyncLoader, isFailed: bool) {.gdsync.} =
  self.isCompleted = not isFailed # Set the loading status
  self.progress = 100
  self.timer.queue_free()
  discard self.onComplete()


method ready*(self :AsyncLoader) {.gdsync.} =
  if Engine.isEditorHint: return
  self.packedScenePath = ""
  self.rootSceneNode = nil
  self.typeOperation = ReplaceImmediate
  self.timer = instantiate Timer
  self.myRes = instantiate PackedScene


proc postReadyInitialization*(self: AsyncLoader, tscnPath: String, rootNode: Node, setOperation: LoadingSceneOperation): bool {.gdsync.} =
  if Engine.isEditorHint: return
  if (tscnPath == "".String) or rootNode.isNil:
    return self.initialized
  self.packedScenePath = tscnPath
  self.rootSceneNode = rootNode
  self.initialized = true
  self.typeOperation = setOperation
  if not ResourceLoader.exists(tscnPath):  # Check if the scene file exists
    printerr(variant "Invalid scene path: ", variant tscnPath)
    return

  discard ResourceLoader.loadThreadedRequest(tscnPath, "".String, true) # Request the scene to be loaded in a separate thread
  discard self.callDeferred("setupUpdateSeconds_internal") # Call it after the current frame is finished
  #discard self.connect("onComplete", self.callable("removeAsyncLoader"))
  
  return self.initialized

# Unloads the loaded scene and cleans up the AsyncScene instance
proc unloadScene*(self: AsyncLoader) {.gdsync.} =
  if Engine.isEditorHint: return
  if not self.initialized:
    printerr(variant ASYNCLOADER_NOT_INIT_MSG)
    return

  if not self.isCompleted: # Check if the scene has been loaded
    printerr(variant "Scene hasn't been loaded yet.")
    return

  if not self.currentSceneNode.isNil:
    self.currentSceneNode.queue_free()


proc removeAsyncLoader(self: AsyncLoader) {.gdsync.} =
  self.queue_free()


# Returns the current status of the scene loading
proc getStatusValue*(self: AsyncLoader): ResourceLoader_ThreadLoadStatus {.gdsync.} =
  if not self.initialized:
    printerr(variant ASYNCLOADER_NOT_INIT_MSG)
    return
  return ResourceLoader.loadThreadedGetStatus(self.packedScenePath)


# Returns the current status of the scene loading as a human-readable string
proc getStatusName*(self: AsyncLoader): String {.gdsync.} =
  if not self.initialized:
    printerr(variant ASYNCLOADER_NOT_INIT_MSG)
    return

  let idx = self.getStatusValue().ord
  # compilation failed with some gdsync template mismatch 
  # when tried to do statusNames[idx]
  return statusNames[idx..idx][0] 


# Changes the current scene to the loaded scene
# This method should only be called after the scene is fully loaded.
proc changeScene*(self: AsyncLoader) {.gdsync.} =
  if Engine.isEditorHint: return
  if not self.initialized:
    printerr(variant ASYNCLOADER_NOT_INIT_MSG)
    return

  
  # Check if the scene has been loaded
  if not self.isCompleted:
    printerr(variant "Scene hasn't been loaded yet.")
    return

  if self.changed: # Prevent multiple scene changes for Replace and Additive operations
    return

  if self.typeOperation == Replace:
    self.changeImmediate_internal()
  elif self.typeOperation == Additive:
    self.additiveScene_internal()

  self.changed = true # Mark the scene as changed
```

I'm frankly new to Nim, so sorry if I made any obvious mistake 😅 
And thanks for help in advance

**Comment by panno8M** [comment]
Hi, thank you for using gdext!
This code has both the bugs that the library has and your coding errors, but with some rework it is workable. I will explain them in turn now.

### Enums used in function arguments and return values must be explicitly registered.

This is the only coding error. The wiki was missing an explanation about Enam, so I will add it.

It can be written anywhere, but directly below the class definition is better.
```nim
AsyncLoader.registerEnum LoadingSceneOperation
```

### {.gdsync.} must not be attached to the forward declaration (Bug)

On this matter, the library has not issued any warning, so I will implement it in the next update.

```nim
# forward declaration
proc getStatusValue*(self: AsyncLoader): int # Modification of return values will be explained later.
proc additiveScene_internal(self: AsyncLoader)
proc changeImmediate_internal(self: AsyncLoader)
proc complete(self: AsyncLoader, isFailed: bool)
```

### Enums built into the engine are not available as arguments or return values. (Bug)

I will fix it to work correctly in the next update. For now (and for the next few days), enums like ResourceLoader_ThreadLoadStatus should be replaced with ints to avoid this problem.

```nim
# forward declaration
proc getStatusValue*(self: AsyncLoader): int #[ <- ]#
```

```nim
# Checks the loading status of the scene
proc checkStatus_internal(self: AsyncLoader) {.gdsync.} =
  if self.isCompleted: # Check if the scene is already loaded
    return

  var status = self.getStatusValue() # Get the loading status

  case ResourceLoader_ThreadLoadStatus #[ <- ]# status:
  ...
```

```nim
# Returns the current status of the scene loading
proc getStatusValue*(self: AsyncLoader): int #[ <- ]# {.gdsync.} =
  if not self.initialized:
    printerr(variant ASYNCLOADER_NOT_INIT_MSG)
    return
  return int #[ <- ]# ResourceLoader.loadThreadedGetStatus(self.packedScenePath)
```

**Comment by NieznanywInternetach** [comment]
@panno8M 
As suggested by the thumbs up, your input fixed the issue on hand. Thank you!
In the meantime, I encountered next 2 issues, the first being relatively small...:
 ```nim
# inside the type definition
  sceneDataPath* {.gdexport.} : NodePath
# inside a function
  var nodePath = self.sceneDataPath.String # error
  var nodePath2 = $self.sceneDataPath      # ok
  self.sceneData = ResourceLoader.loadThreadedGet(nodePath)[].PackedScene.asGdRef
``` 
NodePath can't be converted by String(), but `$` works fine
\+ some VSCode error info, if that helps
```
[{
    "resource": The file,
    "owner": "_generated_diagnostic_collectionname#0",
    "code": "nimsuggest chk",
    "severity": 8,
    "message": "type mismatch: got 'NodePath' for 'self.sceneDataPath' but expected 'string'",
    "source": "nim",
}]
```

... and the other one giving me no clue what went wrong, maybe it's a bad warning again
I get
```
path1\cene_loader.nim(68, 44) template/generic instantiation of `gdsync` from here
path2\gdext\core\userclass\virtuals.nim(48, 8) Error: undeclared identifier: 'ready_emit'
candidates (edit distance, scope distance); see '--spellSuggest':
 (4, 2): 'ready'
 (4, 4): 'readWrite'
 (4, 4): 'ready'
```
when I add
```nim
method ready*(self: AsyncLoaderResource) {.gdsync.} =
  if Engine.isEditorHint: return
  self.timer = instantiate Timer
``` 
to the code below, without it it compiles just fine
```nim
import gdext
import gdext/classes / [gdNode, gdTimer, gdResourceLoader, gdEngine] 
import gdext/classes / [gdMainLoop, gdPackedScene, gdSceneTree]
from gdext/gen/localenums import ResourceLoader_ThreadLoadStatus
import gdext/core / [builtinindex]
import std/[strutils, deques]

# Based on https://github.com/EiTaNBaRiBoA/AsyncScene/blob/main/addons/AsyncSceneManager/AsyncScene.gd
# on MIT license by Eitan (c) 2024 

# Maps ResourceLoader_ThreadLoadStatus values to human-readable strings
const statusNames: array[threadLoadInvalidResource..threadLoadLoaded, string] = [
  "THREAD_LOAD_INVALID_RESOURCE", 
  "THREAD_LOAD_IN_PROGRESS", 
  "THREAD_LOAD_FAILED", 
  "THREAD_LOAD_LOADED"
]

type 
  LoadingSceneOperation = enum  # Defines the different operations that can be performed with the scene loader
    AddRemove,    # Adds scene to the provided root note, and remove it after it's done the job. Useful for temporary scenes, such as pop-ups, characters etc
    AddStay       # Also adds the scene, but it's removed when the AsyncLoader is cleaned up. Useful for UI scenes, or other main components

  ErrorCodes = enum
    FullQueue = 49 # so it doesn't overlap with Godot's Error
    EmptyQueue
    InvalidPath
    NotCompleted

  AsyncLoaderResource* = ptr object of Resource  
    typeOperation* {.gdexport.}: LoadingSceneOperation # Selected operation type for loading the scene
    rootSceneNode* {.gdexport.}: Node       # Node the instance is to be added to
    sceneDataPath* {.gdexport.}: String     # path to load the scene from
    sceneData: GdRef[PackedScene]           # Loaded PackedScene resource
    currentSceneNode: Node                  # Instance of the loaded scene, can be used to remove it later
    timer: Timer                            # Timer for checking the loading status 
    progress*: float = 0                    # Loading progress (0-100)
    isCompleted*: bool = false              # Flag indicating if the scene has been loaded successfully
    toBeRemoved: bool = false               # call AsyncLoader.removeMarkedScenes() to remove
  
  SceneQueue* = ptr object of Resource
    data* {.gdexport.} : Deque[AsyncLoaderResource]

  AsyncLoader* = ptr object of Node
    sceneToDoQueue* {.gdexport.}: SceneQueue  # FIFO, contains data required to play the scene
    sceneStayQueue* {.gdexport.}: SceneQueue  # FIFO with LIFO case, contains scenes already deployed but still in use
    maxQueueSize: int = 25                    # Arbitrary number to limit memory usage. Can be changed later 
    changed: bool = false                     # Flag to prevent multiple scene changes
    

AsyncLoaderResource.registerEnum LoadingSceneOperation
AsyncLoaderResource.registerEnum ErrorCodes
AsyncLoader.registerEnum ErrorCodes


# forward declaration, TODO clean up
proc getStatusValue(self: AsyncLoaderResource): int
proc showNextScene(self: AsyncLoader, forceShow = false): int
proc complete(self: AsyncLoaderResource, isFailed: bool)
proc removeScene*(self: AsyncLoader, sceneNode: Node, doesAlreadyExist = true, forceRemove = false)
proc markSceneForRemoval*(self: AsyncLoader, sceneNode: Node, doesAlreadyExist = true) # user usually want to remove already existing scenes
proc markSceneForRemoval*(self: AsyncLoaderResource)
proc removeMarkedScenes*(self: AsyncLoader, forceRemove = false)
proc displayLoadedScene*(self: AsyncLoaderResource)

# ============ V Problematic V ================ #
method ready*(self: AsyncLoaderResource) {.gdsync.} =
  if Engine.isEditorHint: return
  self.timer = instantiate Timer
# ============ ========== ================ #

# Called when the scene loading is complete
proc complete(self: AsyncLoaderResource, isFailed: bool) =
  self.isCompleted = not isFailed # Set the loading status
  self.progress = 100
  self.timer.queue_free()
  
# Checks the loading status of the scene
proc checkStatus_internal(self: AsyncLoaderResource) =
  if self.isCompleted: # Check if the scene is already loaded
    return

  var status = self.getStatusValue() # Get the loading status
  case status.ResourceLoader_ThreadLoadStatus:
  of threadLoadLoaded:  # v from a Ref to a Resource to a Ref to a PackedScene
    self.sceneData = ResourceLoader.loadThreadedGet(self.sceneDataPath)[].PackedScene.asGdRef
    self.complete(false) # Mark the scene as loaded and stop the timer
    self.displayLoadedScene()

  of threadLoadInvalidResource, threadLoadFailed:
    printerr(variant &"AsyncLoaderResource: ERROR during file loading: {statusNames[status.ord]}")
    self.complete(true) # Mark the scene loading as failed and stop the timer
  
  of threadLoadInProgress:
    var progressArr: Array # v returns a single float into the array
    let status2 = ResourceLoader.loadThreadedGetStatus(self.sceneDataPath, progressArr)
    if status2 != threadLoadInProgress:
      printerr(variant &"AsyncLoaderResource: ERROR during loading progress check-up: {statusNames[status2.ord]}")
      self.complete(true)
    self.progress = progressArr[0].get(Float) * 100


# Returns the current status of the scene loading
proc getStatusValue(self: AsyncLoaderResource): int =
  return ResourceLoader.loadThreadedGetStatus(self.sceneDataPath).int


proc addSceneToQueue(self: AsyncLoader, sceneObject: AsyncLoaderResource): int {.gdsync.} =
  let isToDoFull = self.maxQueueSize <= self.sceneToDoQueue.data.len
  let isStayFull = self.maxQueueSize <= self.sceneStayQueue.data.len
  if isToDoFull or isStayFull:
    printerr( variant ("AsyncLoader - Scene queue reached maximum capacity ( ToDoQueue: $1, StayQueue: $2, Max: $3 )." &
              "\nRemove some scenes first or increase the limit.") % [$self.sceneToDoQueue.data.len, $self.sceneStayQueue.data.len, $self.maxQueueSize])
    return FullQueue.int
  
  case sceneObject.typeOperation:
  of AddRemove: # in most cases, that's what you want to go with
    #self.sceneToDoQueue.addFirst(self, SceneObject)
    self.sceneToDoQueue.data.addFirst(sceneObject)
  of AddStay: # for special cases, mostly used by showNextScene()
    self.sceneStayQueue.data.addFirst(sceneObject)
  return Error.ok.int


proc validateNextScene(self: AsyncLoader): int =
  if self.maxQueueSize <= self.sceneStayQueue.data.len:
    printerr( variant ("AsyncLoader - Scene queue reached maximum capacity (StayQueue: $1, Max: $2)." &
              "\nRemove some scenes first or increase the limit.") % [$self.sceneStayQueue.data.len, $self.maxQueueSize])
    return FullQueue.int
  if self.sceneTodoQueue.data.len < 1:
    printerr( variant "AsyncLoader - No scenes to be shown, load more with addSceneToQueue(...)")
    return EmptyQueue.int
  let newScene = self.sceneToDoQueue.data.peekLast()
  if not ResourceLoader.exists(newScene.sceneDataPath):  # Check if the scene file exists
    printerr(variant "AsyncLoader - Invalid scene path: ", variant newScene.sceneDataPath)
    return InvalidPath.int
  return Error.ok.int


proc showNextScene(self: AsyncLoader, forceShow = false): int {.gdsync.} =
  var errorCode = self.validateNextScene()
  if errorCode != Error.ok.int:
    return errorCode.int
  
  var 
    lastAddedScene, newScene: AsyncLoaderResource
    removeSceneFlag = false

  if self.sceneStayQueue.data.len > 0:
    lastAddedScene = self.sceneStayQueue.data.peekFirst()
    if not lastAddedScene.isCompleted and not forceShow:
      printerr(variant "Loading of the previous scene is not finished, wait till it's ready or use forceShow=true")
      return NotCompleted.int
    if lastAddedScene.typeOperation == AddRemove: # not AddStay so it's to be removed
      removeSceneFlag = true

  # TODO add preloading    
  errorCode = ResourceLoader.loadThreadedRequest(newScene.sceneDataPath, "PackedScene".String, useSubThreads=true).int 
  if errorCode != Error.ok.int:
    printerr(variant &"AsyncLoader - Can't load the resource, Error code: {errorCode} with string: ", variant errorString(errorCode.int))
    return errorCode.int

  if removeSceneFlag: # so we don't lose data in case of Error returns in between
    lastAddedScene = self.sceneStayQueue.data.popFirst()
    lastAddedScene.markSceneForRemoval()
    self.removeMarkedScenes(forceRemove=forceShow)
  
  newScene = self.sceneToDoQueue.data.popFirst()
  discard newScene.callDeferred("setupTimer") # returns null, not function's result
  self.sceneStayQueue.data.addFirst(newScene)
  return Error.ok.int
    

proc displayLoadedScene*(self: AsyncLoaderResource) {.gdsync.} = 
  self.currentSceneNode = self.sceneData[].instantiate()
  discard self.rootSceneNode.callDeferred("add_child", variant self.currentSceneNode) # returns null, not function's result


proc removeScene*(self: AsyncLoader, sceneNode: Node, doesAlreadyExist = true, forceRemove = false) {.gdsync.} =
  var queueToOperate = if doesAlreadyExist: self.sceneStayQueue else: self.sceneToDoQueue
  for scene in queueToOperate.data:
    if scene.currentSceneNode == sceneNode:
      if scene.isCompleted == false:
        case forceRemove:
        of false:
          printerr(variant &"Node from resource with path {scene.sceneDataPath} was't loaded up yet. Use forceRemove=true to bypass it")
          return
        of true:
          if not scene.timer.isNil():
            scene.timer.stop()
            scene.timer.queue_free()
      if not scene.currentSceneNode.isNil:
        scene.currentSceneNode.queue_free()        
      return
  printerr(variant &"Couldn't find requested Node with provided setting doesAlreadyExist: {doesAlreadyExist}")
  

proc markSceneForRemoval*(self: AsyncLoader, sceneNode: Node, doesAlreadyExist = true) {.gdsync.} =
  var queueToOperate = if doesAlreadyExist: self.sceneStayQueue else: self.sceneToDoQueue
  for scene in queueToOperate.data:
    if scene.currentSceneNode == sceneNode:
      scene.toBeRemoved = true
      return
  printerr(variant &"Couldn't find requested Node with provided setting doesAlreadyExist: {doesAlreadyExist}")


proc markSceneForRemoval*(self: AsyncLoaderResource) {.gdsync.} =
  self.toBeRemoved = true

proc removeDependentNodes*(self: SceneQueue, forceRemove: bool): seq[int] = 
  for idx, scene in self.data.pairs():
    if not scene.toBeRemoved:
        result.add(idx)
        continue
    if not scene.isCompleted:
      if not forceRemove:
        result.add(idx)
        continue
      if not scene.timer.isNil:
        scene.timer.stop()
        scene.timer.queue_free()
    if not scene.timer.isNil:
      scene.currentSceneNode.queue_free()


proc removeMarkedScenes*(self: AsyncLoader, forceRemove = false) {.gdsync.} =
  for queue in @[self.sceneToDoQueue, self.sceneStayQueue]:
    var idxToStay = removeDependentNodes(queue, forceRemove)
    var newQueue: Deque[AsyncLoaderResource]
    for idx in idxToStay.items():
      newQueue.addFirst(queue.data[idx])
    queue.data = newQueue
  

# Returns the current status of the scene loading as a human-readable string
proc getStatusName*(self: AsyncLoaderResource): String {.gdsync.} =
  let idx = self.getStatusValue()
  # compilation failed with gdsync template mismatch when tried to do statusNames[idx]
  return statusNames[idx..idx][0] 


proc setupTimer(self: AsyncLoaderResource) =
  self.rootSceneNode.add_child(self.timer)

  self.timer.one_shot = false
  self.timer.autostart = true
  self.timer.setWaitTime(0.1)

  discard self.timer.connect("timeout", self.callable("checkStatus_internal"))
  self.timer.start()


proc removeAsyncLoader(self: AsyncLoader) {.gdsync.} =
  if not self.isNil: # you never know with user inputs, ammirite?
    self.queue_free()
```
I hope working on 0.5.0 goes well. Again, thanks for help and amazing work with the extention. Cheers!

**Comment by panno8M** [comment]
### NodePath can't be converted by String()

Use `gdstring` for example:

```nim
let gdstr: String = gdstring nodepath
```

gdstring is a constructor for String (not string), and can be used to create a String from string and StringName as well.

### and the other one giving me no clue what went wrong...

Use `onInit` method instead:
```nim
method onInit*(self: AsyncLoaderResource)  =
  if Engine.isEditorHint: return
  self.timer = instantiate Timer
```

onInit is like `_init` in GDScript.

#### What happened?

The ready method is a callback that is called when a **Node** is added to the scene tree.

Since the Resource that AsyncLoaderResource inherits from is not a Node, it seems that you are panicking by trying to call a callback that does not exist. (Even so, the error message is confusing. I'll try to improve it a bit.)

**Comment by panno8M** [comment]
Fix is complete; should eliminate the process of converting int and enums :)

I close this issue with thanks for your report. If the above response and fixes did not resolve the issue, please reopen it. Please create a new issue if a new problem arises.
